// Standalone host through the CLI adapter: two hosts in one process, liftHarness, sessionEnv.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { check } from './check.mjs';
import { expectFail } from './console.mjs';
import { makeSandbox, writeHostConfig } from './sandbox.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const { hostOf, isPromptobusHost } = await import(path.join(here, '..', 'lib', 'host.js'));
const { createStandaloneHost, HOST_KIND } = await import(path.join(here, '..', 'dist', 'host-index.js'));
const { liftHarness, memoryRule, sessionEnv, sessionEnvNote } = await import(path.join(here, '..', 'lib', 'spawn.js'));
const { renderBusHook, planPromptobusHooks } = await import(path.join(here, '..', 'dist', 'hooks.js'));
const store = await import(path.join(here, '..', 'lib', 'store.js'));
const { promptobusHome: storeHome } = store;
const { status } = await import(path.join(here, '..', 'lib', 'status.js'));
const { history } = await import(path.join(here, '..', 'lib', 'history.js'));
const { dismiss } = await import(path.join(here, '..', 'lib', 'dismiss.js'));
const { prune } = await import(path.join(here, '..', 'lib', 'prune.js'));

const thrown = (fn) => {
  try { fn(); return { threw: false, msg: '' }; }
  catch (e) { return { threw: true, msg: String(e.message ?? e) }; }
};

const a = makeSandbox('promptobus-host-a-');
const b = makeSandbox('promptobus-host-b-');
writeHostConfig(a, { tools: ['claude', 'cursor'] });
writeHostConfig(b, { tools: ['claude'] });

const hostA = createStandaloneHost({
  cwd: a, commandName: 'alpha', extraEnv: { MARK: 'a' }, binPath: '/bin/alpha',
});
const hostB = createStandaloneHost({
  cwd: b, commandName: 'beta', extraEnv: { MARK: 'b' }, binPath: '/bin/beta',
});

check('two standalone hosts in one process are different objects with different roots',
  hostA !== hostB && hostA.workspaceRoot() === a && hostB.workspaceRoot() === b
  && hostA.kind === HOST_KIND && isPromptobusHost(hostA) && isPromptobusHost(hostB),
  `${hostA.workspaceRoot()} / ${hostB.workspaceRoot()}`);

check('hosts declare tools independently: cursor lifts only on the first',
  liftHarness(hostA, 'cursor').id === 'cursor'
  && thrown(() => liftHarness(hostB, 'cursor')).threw,
  thrown(() => liftHarness(hostB, 'cursor')).msg);

check('sessionEnvNote reads extraEnv of the host that was passed',
  hostA.extraEnv().MARK === 'a' && hostB.extraEnv().MARK === 'b'
  && sessionEnvNote({ options: { envDrop: ['X'] } }, hostA).includes('MARK=a')
  && sessionEnvNote({ options: { envDrop: ['X'] } }, hostB).includes('MARK=b')
  && !sessionEnvNote({ options: { envDrop: ['X'] } }, hostA).includes('MARK=b'),
  sessionEnvNote({ options: { envDrop: ['X'] } }, hostA));

check('hostOf(string) builds a standalone host; hostOf(host) returns the same object',
  hostOf(a).commandName === 'promptobus' && hostOf(hostA) === hostA
  && hostOf(hostB) === hostB,
  hostOf(a).id);

const hookA = renderBusHook(hostA);
const hookB = renderBusHook(hostB);
check('bus hook substitutes host commandName, not a hardcoded name',
  hookA.includes('Generated by alpha sync') && hookB.includes('Generated by beta sync'),
  hookA.split('\n')[1]);

const planned = planPromptobusHooks(hostA);
check('hook plan writes the standalone bus-hook path',
  planned.rel === path.join('.promptobus', 'hooks', 'bus.mjs')
  && planned.text.includes('Generated by alpha sync'),
  planned.rel);

const standaloneSrc = readFileSync(path.join(here, '..', 'src', 'standalone.ts'), 'utf8');
const banned = ['ati', 'agents'].join('-');
const forbidden = [banned, ['.', 'agents/'].join(''), ['ATI', '_'].join(''), 'memory-hooks', 'gitlab.ati']
  .filter((n) => standaloneSrc.includes(n));
check('standalone host source does not contain a foreign workspace layout',
  forbidden.length === 0, forbidden.join(', '));

const fakeDriver = {
  sessionEnv: (base, extra) => ({ ...base, ...extra }),
  options: { envDrop: [] },
  phrases: { tool: (server, name) => `${server}__${name}` },
};
check('memoryRule on a standalone host is empty',
  memoryRule(fakeDriver, hostA) === '',
  memoryRule(fakeDriver, hostA));
const envA = sessionEnv(fakeDriver, { PATH: '/bin' }, hostA);
const envB = sessionEnv(fakeDriver, { PATH: '/bin' }, hostB);
check('sessionEnv takes extraEnv of the host that was passed',
  envA.MARK === 'a' && envB.MARK === 'b', JSON.stringify({ a: envA.MARK, b: envB.MARK }));

check('standalone host contract members that otherwise would have no call site',
  hostA.locale === 'en'
  && hostA.promptobusHome() === storeHome(a, hostA)
  && hostA.toolsManifestRel() === 'promptobus.json'
  && hostA.installManifestRel() === path.join('.promptobus', 'manifest.json')
  && hostA.cloneOf(a) === null
  && hostA.inWorkspace(a)
  && !hostA.inWorkspace(b)
  && hostA.cloneHint('x') === 'git clone <url> x'
  && hostA.formatNpx(['clone', 'x']) === 'npx alpha clone x'
  && hostA.legacyLayout() === null,
  `${hostA.promptobusHome()} ${hostA.toolsManifestRel()}`);

mkdirSync(path.join(a, 'skills'), { recursive: true });
writeFileSync(path.join(a, 'promptobus.json'), `${JSON.stringify({
  commandName: 'fromfile', tools: ['claude'], skills: 'skills', locale: 'ru', version: '9.9.9',
})}\n`);
const fromFile = createStandaloneHost({ cwd: a });
check('createStandaloneHost reads promptobus.json from cwd',
  fromFile.commandName === 'fromfile'
  && fromFile.declaredTools().join(',') === 'claude'
  && fromFile.skillsDir() === path.join(a, 'skills')
  && fromFile.locale === 'ru'
  && fromFile.version === '9.9.9',
  `${fromFile.commandName} ${fromFile.declaredTools()}`);

// A host may put its bus somewhere other than `<workspaceRoot>/.promptobus`. Every command
// must ask the host for that path, just as spawn, review, and done already do; rebuilding it
// from workspaceRoot silently opens a different, empty journal.
const customRoot = makeSandbox('promptobus-host-custom-home-');
const customHome = path.join(customRoot, 'bus-elsewhere');
writeHostConfig(customRoot);
const customHost = createStandaloneHost({
  cwd: customRoot, home: customHome, version: '0.5.1', binPath: '/bin/promptobus-custom',
});
store.bus(customHome, { cli: customHost.version });
const visible = store.createTask(customHome, {
  id: 'host-home-t20260909-172500', title: 'host-selected journal', owner: null,
});
store.upsertParticipant(customHome, visible.id, store.participantRecord('worker:custom'));
store.sendMessage(customHome, visible.id, {
  from: store.ORCHESTRATOR, to: 'worker:custom', type: 'task', body: 'visible through custom home',
});
store.readInbox(customHome, visible.id, 'worker:custom');
const old = store.createTask(customHome, {
  id: 'host-prune-t20260909-172501', title: 'closed in custom home', owner: null,
});
store.closeTask(customHome, old.id);

const customStatus = expectFail(() => status(customHost, { sessions: {} }));
check('status reads the store home declared by the host',
  !customStatus.failed && customStatus.out.includes(visible.id), customStatus.out);

const customHistory = expectFail(() => history(customHost, { task: visible.id, all: true }));
check('history reads the store home declared by the host',
  !customHistory.failed && customHistory.out.includes('visible through custom home'), customHistory.out);

const customDismiss = expectFail(() => dismiss(customHost, { task: visible.id, address: 'worker:custom' }));
const dismissed = store.participantOf(store.readTask(customHome, visible.id), 'worker:custom')?.metadata.dismissed;
check('dismiss writes the store home declared by the host',
  !customDismiss.failed && typeof dismissed === 'string', `${customDismiss.out} · dismissed=${dismissed}`);

const customPrune = expectFail(() => prune(customHost, { olderThan: 0 }));
check('prune reads the store home declared by the host',
  !customPrune.failed && customPrune.out.includes(old.id) && /would be removed/.test(customPrune.out),
  customPrune.out);

function javascriptFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) return javascriptFiles(file);
    return entry.isFile() && entry.name.endsWith('.js') ? [file] : [];
  });
}

const stripComments = (text) => text
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/(^|[^:'"\\])\/\/[^\n]*/g, '$1');

function callsFreePromptobusHome(source) {
  const text = stripComments(source);
  for (const match of text.matchAll(/\bpromptobusHome\s*\(/g)) {
    const before = text.slice(0, match.index);
    if (/[$\w]$/.test(before) || before.trimEnd().endsWith('.')) continue;
    return true;
  }
  return false;
}

const repoRoot = path.join(here, '..');
const homeGateRoots = [path.join(repoRoot, 'lib'), path.join(repoRoot, 'bin')];
const allowedFreeHomeCalls = new Set([path.join(repoRoot, 'lib', 'store.js')]);
check('store home gate ignores comments and host member calls but detects an aliased free call',
  !callsFreePromptobusHome('// promptobusHome(root, host)')
  && !callsFreePromptobusHome('/* promptobusHome(root, host) */ host.promptobusHome()')
  && callsFreePromptobusHome('const rootAlias = host.workspaceRoot(); promptobusHome(rootAlias, host);'),
  'comment or member classification failed');
const homeBypasses = homeGateRoots.flatMap(javascriptFiles)
  .filter((file) => !allowedFreeHomeCalls.has(file))
  .filter((file) => callsFreePromptobusHome(readFileSync(file, 'utf8')))
  .map((file) => path.relative(repoRoot, file));
check('store commands never rebuild a host home from workspaceRoot',
  homeBypasses.length === 0, homeBypasses.join(', '));
