#!/usr/bin/env node
// Generated by __COMMAND__ sync. Edits are overwritten — the source lives in the Promptobus package.
//
// PostToolUse on the bus tools: one session-feed line per exchange event —
//
//   {mark }Sent {type} → {readable name of the addressee session} — {body excerpt}
//   {mark }Received {type} from {readable name of the sender session} — {body excerpt}
//
// The name is how the participant appears in the harness session list; the address and
// id stay in the reply. A line of its own, with an excerpt, goes to what matters, and
// EVERY `status` from one mailbox collapses into a roll —
//
//   • {count} status: {name} · {name} · {name}
//
// — and that line sits after what matters, so it does not push it down; a single status
// uses the same roll of one. The type is always named; an empty body means a line with
// no ` — …` tail. Silence is a working outcome: the hook must not interfere with the
// call, so any surprise ends as empty stdout.
const SEP = "\n";
const MAX = 600;
const LINE = 144;
const SHOWN = 4;
// Reserve room for the "+ N more" tail up front: it says how many the person did not see.
const TAIL_COST = 12;
// The identity tail of the reply (PROMPTOBUS_HOME, address, task) is diagnostics: in the
// feed it takes more room than the exchange itself, so the summary is clipped before it.
const IDENTITY = ' · PROMPTOBUS_HOME=';
// Mailbox message heading: «### <type> from <name> · address <address> · <ts>».
const HEAD = '### ';
// Boundary between the readable name and the machine tail (server.js).
const ADDR = ' · address ';
// First line of a send reply: «sent <type> → <name> · address <address> · id <id>».
const SENT = 'sent ';
// Name and excerpt share one line: a pair of lines would give the second its own client prefix.
const DASH = ' — ';
// Empty mailbox reply — and exactly that: silence is compared to the word WHOLE, not by
// «no events parsed». Two other lawful replies arrive without parsed events (`FOREIGN MAILBOX`
// and `BROKEN MESSAGE`) — they say the correspondence went elsewhere, and staying silent about them costs more.
const EMPTY = 'empty';
// The type that does not get a line of its own: most of a run is statuses, and four
// "took the assignment" lines used to push the waiting question out of the feed.
const ROUTINE = 'status';
// Opening of the status roll and the separator between names in it.
const ROLL = '• ';
const ROLL_SEP = ' · ';
// Marks for what matters — the same as the CLI: a question waits for an answer, a result closes the track.
const MARKS = { question: '⚠', result: '✔' };

function text(value) {
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) return value.map(text).filter(Boolean).join('\n');
  if (value && typeof value === 'object') {
    if (typeof value.text === 'string') return value.text;
    if (Array.isArray(value.content)) return text(value.content);
  }
  return '';
}

// Clip on a word boundary; if there is no word near the limit (a long path, an id) —
// cut as-is. No ellipsis: the mark costs room, and the break is visible without it.
function clip(s, max) {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const space = cut.lastIndexOf(' ');
  return (space > max * 0.6 ? cut.slice(0, space) : cut).trimEnd();
}

// The ` · address ` mark is searched FROM THE END: the same ` · ` that splits parts of the
// line is lawful in the name itself. No mark (foreign format) — take what is before the first separator.
function split(raw) {
  const at = raw.lastIndexOf(ADDR);
  if (at === -1) return { head: raw.split(' · ')[0].trim(), addr: '' };
  return { head: raw.slice(0, at).trim(), addr: raw.slice(at + ADDR.length).split(' · ')[0].trim() };
}

// Marks are looked up with hasOwnProperty: `MARKS['constructor']` would otherwise come from the prototype.
function mark(type) {
  return Object.prototype.hasOwnProperty.call(MARKS, type) ? MARKS[type] + ' ' : '';
}

// Name and excerpt share the line ceiling, otherwise a long name would crowd out other messages.
// A heading longer than the ceiling leaves the line with no excerpt at all, rather than cutting it into junk.
function compose(head, said) {
  const room = LINE - head.length - DASH.length;
  return said && room > 0 ? head + DASH + clip(said, room) : head;
}

// First paragraph: the reply tail is separated by a blank line and does not enter the excerpt.
function para(lines) {
  const body = [];
  for (const raw of lines) {
    const line = raw.trim();
    if (line) body.push(line);
    else if (body.length) break;
  }
  return body.join(' ');
}

// A body opening that repeats the sender is stripped: "worker:store took the assignment"
// right after the same session name reads as the name twice. Forms are the address, the
// bare name, and the same with a role in front; the long one is tried first, otherwise
// `store` would eat the start of `worker:store`. A separator is required after the name,
// otherwise "store.js rewritten" would be stripped. An empty cut is rolled back.
function trimSelf(body, addr, name) {
  if (!name) return body;
  const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const forms = [addr, name].filter(Boolean).sort((a, b) => b.length - a.length).map(esc).join('|');
  const re = new RegExp('^(?:(?:воркер|ревьюер|worker|reviewer)\\s+)?(?:' + forms + ')(?::\\s*|\\s+)', 'i');
  const cut = body.replace(re, '').trim();
  return cut ? cut : body;
}

// Mailbox messages: heading plus the first body paragraph. What matters is parsed
// line by line; statuses accumulate names onto one roll; a name is not repeated —
// "• 3 status: store", not three times.
function mailbox(lines) {
  const out = [];
  const names = [];
  let routine = 0;
  for (let i = 0; i < lines.length; i += 1) {
    if (lines[i].indexOf(HEAD) !== 0) continue;
    const { head, addr } = split(lines[i].slice(HEAD.length));
    const body = [];
    for (let j = i + 1; j < lines.length && lines[j].indexOf(HEAD) !== 0; j += 1) body.push(lines[j]);
    const said = para(body);
    const m = /^(\S+)\s+from\s+(.+)$/.exec(head);
    // The heading did not parse — take it as-is: a line without a type is better than silence.
    if (!m) { out.push(compose(head, said)); continue; }
    if (m[1] === ROUTINE) {
      routine += 1;
      if (names.indexOf(m[2]) === -1) names.push(m[2]);
      continue;
    }
    const bare = addr.indexOf('worker:') === 0 ? addr.slice(7) : addr;
    out.push(compose(mark(m[1]) + 'Received ' + m[1] + ' from ' + m[2], trimSelf(said, addr, bare)));
  }
  // The roll is clipped to the same line ceiling. A trailing separator after the clip
  // is removed: `clip` cuts on a word boundary, and the feed used to show "• 12 status: A · B ·".
  const roll = routine
    ? [clip(ROLL + routine + ' ' + ROUTINE + ': ' + names.join(ROLL_SEP), LINE).replace(/\s*·$/, '')]
    : [];
  return { out: out, roll: roll };
}

// Send: the addressee name comes from the reply, the excerpt from `tool_input.body`,
// because a send reply carries no body of its own and must not.
function sent(lines, input) {
  for (const raw of lines) {
    const s = raw.trim();
    if (s.indexOf(SENT) !== 0) continue;
    const at = s.indexOf(IDENTITY);
    const { head } = split(at === -1 ? s : s.slice(0, at));
    const m = /^sent\s+(\S+)\s+→\s+(.+)$/.exec(head);
    if (!m) return [];
    return [compose(mark(m[1]) + 'Sent ' + m[1] + ' → ' + m[2], para(String(input?.body ?? '').split('\n')))];
  }
  return [];
}

let raw = '';
process.stdin.setEncoding('utf8');
for await (const chunk of process.stdin) raw += chunk;

let line = '';
try {
  const event = JSON.parse(raw);
  const tool = String(event.tool_name ?? '');
  const lines = text(event.tool_response).split('\n');
  const first = lines.map((s) => s.trim()).find(Boolean) ?? '';
  const at = first.indexOf(IDENTITY);
  const summary = clip((at === -1 ? first : first.slice(0, at)).trim(), MAX);

  const got = tool.endsWith('mailbox') ? mailbox(lines) : { out: [], roll: [] };
  const all = tool.endsWith('send') ? sent(lines, event.tool_input) : got.out;
  // The status roll comes AFTER what matters: routine must not push down a question that waits for an answer.
  const roll = got.roll;
  // The summary stays where it is the content of the reply — on a send. An empty mailbox
  // gets no line at all: "empty" says nothing the person does not already see nearby
  // (the warden postcard), and it costs as much feed room as a message.
  const bare = all.length + roll.length === 0 && !(tool.endsWith('mailbox') && summary === EMPTY);
  const parts = bare ? [summary] : [];
  let used = parts.length ? parts[0].length : 0;
  // Room for the tail is held at any event count, not only past SHOWN: the list also
  // breaks on the overall limit, and then the tail would be appended past it and the
  // final clip would cut it off. The same trick holds room for the roll — otherwise
  // routine would vanish in silence.
  const reserve = (all.length ? TAIL_COST : 0) + (roll.length ? SEP.length + roll[0].length : 0);
  const shown = [];
  for (const m of all) {
    if (shown.length >= SHOWN - roll.length) break;
    const cost = (parts.length + shown.length ? SEP.length : 0) + m.length;
    if (used + cost + reserve > MAX) break;
    shown.push(m);
    used += cost;
  }
  parts.push(...shown, ...roll);
  // Statuses do not go into the tail: the roll already named their count; only what matters went unseen.
  if (all.length > shown.length) parts.push('+ ' + (all.length - shown.length) + ' more');
  line = clip(parts.filter(Boolean).join(SEP), MAX);
} catch {
  line = '';
}
if (line) process.stdout.write(JSON.stringify({ systemMessage: line }) + '\n');
